# Generated by Django 4.2 on 2024-04-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True, max_length=200, null=True)),
                ('likenum', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
    ]
